In [1]:
import requests
import pandas as pd
import numpy as np

response_API = requests.get('https://api.openalex.org')
response_API.status_code # 200 means success

200

In [20]:
# PaperAuthorAffiliations


# 333,457 affiliated works for University of Washington

# https://api.openalex.org/works?filter=institutions.id:I201448701


UW_works_url = "https://api.openalex.org/works?filter=institutions.id:I201448701&cursor=IlszMiwgJ2h0dHBzOi8vb3BlbmFsZXgub3JnL1czMTg1MzQ4NTg4J10i"
UW_works = requests.get(UW_works_url).json()

rows = []

for r in UW_works['results']:
    if 'mag' in r['ids']:
        magid = r['ids']['mag']
    else:
        magid = np.nan

    for a in r['authorships']:
        
        author_id = int(a['author']['id'].rsplit('/A', 1)[-1])

        if len(a['institutions']) != 0:
            last_instition = a['institutions'][-1:][0]
            
            if 'id' in last_instition and last_instition['id'] != None:
                aff_id = int(last_instition['id'].rsplit('/I', 1)[-1])
            else:
                aff_id = np.nan
            
            if 'display_name' in last_instition:
                display_name = last_instition['display_name']
            else:
                display_name = np.nan
            
            if 'country_code' in last_instition:
                country_code = last_instition['country_code']
            else:
                country_code = np.nan
            
        else:
            aff_id = np.nan
            display_name = np.nan
            contry_code = np.nan
    

        rows.append([magid, author_id, aff_id, display_name, country_code, 
                     a['author_position'], a['author']['display_name']])
    
df = pd.DataFrame(rows, columns=["Paper_id", "Author_ID", "Affiliation_ID", 
                                          "Affiliation_name", "Country_code", 
                                          "Author_sequence_number", "Author_name"])
df

,Paper_id,Author_ID,Affiliation_ID,Affiliation_name,Country_code,Author_sequence_number,Author_name
0,3193316912,3133591803,18959387.0,Hitec,None,first,Bo Yang
1,3193316912,2890133243,185261750.0,University of Toronto,CA,middle,Chengjin Wang
2,3193316912,2132535321,18959387.0,Hitec,None,middle,Xin Cheng
3,3193316912,2137639100,18959387.0,Hitec,None,middle,Yongli Zhang
4,3193316912,2605572716,18959387.0,Hitec,None,middle,Wei Li
...,...,...,...,...,...,...,...
202,600630832,2205819562,139264467.0,Seoul National University,KR,last,Sung Soo Ahn
203,627466247,305488809,NaN,NaN,KR,first,Joseph A. Beavo
204,627466247,2103096524,NaN,NaN,KR,middle,Sharron H. Francis
205,627466247,2207115785,201448701.0,University of Washington,US,last,Miles D. Houslay
206,63710923,3176163762,201448701.0,University of Washington,US,first,M. Bothwell

In [ ]:
UW_works_url_with_cursor = 'https://api.openalex.org/works?filter=institutions.id:I201448701&cursor={}'


cursor = '*'
PaperAuthorAffiliations_rows = []

count = 1

# loop through pages
while cursor:
    UW_works_url = UW_works_url_with_cursor.format(cursor)
    print("\n" + str(count) + ": " + UW_works_url)

    UW_works = requests.get(UW_works_url).json()
        
    for r in UW_works['results']:
        if 'mag' in r['ids']:
            magid = r['ids']['mag']
        else:
            magid = np.nan

        for a in r['authorships']:
        
            author_id = int(a['author']['id'].rsplit('/A', 1)[-1])
            
            if len(a['institutions']) != 0:
                last_instition = a['institutions'][-1:][0]

                if 'id' in last_instition and last_instition['id'] != None:
                    aff_id = int(last_instition['id'].rsplit('/I', 1)[-1])
                else:
                    aff_id = np.nan

                if 'display_name' in last_instition:
                    display_name = last_instition['display_name']
                else:
                    display_name = np.nan

                if 'country_code' in last_instition:
                    country_code = last_instition['country_code']
                else:
                    country_code = np.nan
            else:
                aff_id = np.nan
                display_name = np.nan
                contry_code = np.nan


            PaperAuthorAffiliations_rows.append([magid, author_id, aff_id, 
                                                 display_name, 
                                                 contry_code, 
                                                 a['author_position'], 
                                                 a['author']['display_name']])

    # update cursor to meta.next_cursor
    cursor = UW_works['meta']['next_cursor']
    
    count += 1


PaperAuthorAffiliations_df = pd.DataFrame(PaperAuthorAffiliations_rows, 
                                          columns=["Paper_id", "Author_ID", "Affiliation_ID", 
                                          "Affiliation_name", "Country_code", 
                                          "Author_sequence_number", "Author_name"])
PaperAuthorAffiliations_df